# Generated by Django 2.2.24 on 2021-10-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('date_requirement', models.DateField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('hours_discount', models.IntegerField()),
            ],
        ),
    ]
