# Generated by Django 2.2.24 on 2022-01-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='days',
            field=models.IntegerField(),
        ),
    ]
