# Generated by Django 2.2.24 on 2021-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
