# Generated by Django 2.2.24 on 2021-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
