# Generated by Django 2.2.24 on 2021-11-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason', to='employee.Reason'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
