# Generated by Django 2.2.24 on 2021-11-06 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211103_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason', to='employee.Reason'),
        ),
    ]
