# Generated by Django 2.2.24 on 2021-11-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211114_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
