# Generated by Django 2.2.24 on 2021-12-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_jefatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefatura',
            name='employee',
        ),
    ]
