# Generated by Django 2.2.24 on 2021-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211227_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='hours_discount',
            field=models.IntegerField(),
        ),
    ]
