# Generated by Django 2.2.24 on 2021-12-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20211227_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='hours_discount',
            field=models.IntegerField(blank=True),
        ),
    ]
