# Generated by Django 2.2.24 on 2021-10-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20211028_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='date_start',
            field=models.DateField(),
        ),
    ]
