# Generated by Django 2.2.24 on 2021-12-07 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_jefatura_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jefatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefatura', to='employee.Jefatura'),
        ),
    ]
