# Generated by Django 2.2.24 on 2022-01-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_holidays_days_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='date_last_holidays',
            field=models.DateField(blank=True, null=True),
        ),
    ]
