# Generated by Django 2.2.24 on 2021-11-26 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_reason_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
