# Generated by Django 2.2.24 on 2021-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_jefatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='penalty',
            field=models.BooleanField(default=False),
        ),
    ]
