# Generated by Django 2.2.24 on 2021-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_jefatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.AlterField(
            model_name='holidays',
            name='days',
            field=models.IntegerField(verbose_name=30),
        ),
    ]
