# Generated by Django 2.2.24 on 2022-01-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_holidays_date_last_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='date_requirement',
        ),
    ]
