# Generated by Django 2.2.24 on 2021-12-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_reason_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeHolidays', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='days',
            field=models.IntegerField(),
        ),
    ]
