# Generated by Django 2.2.24 on 2021-12-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_jefatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_penalty', models.IntegerField()),
                ('observations', models.TextField()),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='employee.Requirements')),
            ],
        ),
    ]
