# Generated by Django 2.2.24 on 2021-11-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211126_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
