# Generated by Django 2.2.24 on 2021-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211217_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jefatura',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
