# Generated by Django 2.2.24 on 2021-11-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211029_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='employee.Employee'),
        ),
    ]
