# Generated by Django 2.2.24 on 2022-01-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_holidays_date_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='days_take',
            field=models.IntegerField(default=0),
        ),
    ]
