# Generated by Django 2.2.24 on 2021-11-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_requirements_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
