# Generated by Django 2.2.24 on 2021-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20211101_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
