# Generated by Django 2.2.24 on 2021-11-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20211101_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
